version: '3.3'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=ville.vainikka@valtori.fi"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
    container_name: "traefik"
    ports:
        - 80:80
        - 443:443
    network:
        - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.yaml:/traefik.yaml
      - $PWD/traefik_dynamic.yaml:/traefik_dynamic.yaml
      - $PWD/acme.json:/acme.json

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`dmarc.valtor.fi`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=myresolver"