version: "3.5"
networks:
    default:
      external:
        name: traefik-lan
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:latest
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    labels:
    - "traefik.enable=true"
#        - "traefik.http.services.dmarc-grafana.loadbalancer.server.port=3000"
    - "traefik.http.routers.dmarc-grafana.rule=Host(`hive.valtor.fi`)"
    - "traefik.http.routers.dmarc-grafana.entrypoints=websecure"
    - "traefik.http.routers.dmarc-grafana.tls.certresolver=resolveri"