version: "2"
networks:
  default:
    name: hive-lan
  traefik-lan:
    external: true
  
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
#    volumes:
#      - /opt/eldata:/usr/share/elasticsearch/data
#    ports:
#      - "9201:9200"
#      - "9301:9300"

  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"

  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: --cortex-port 9001
    networks:
      - default
      - traefik-lan
    labels:
    - "traefik.enable=true"
#        - "traefik.http.services.dmarc-grafana.loadbalancer.server.port=3000"
    - "traefik.http.routers.router-hive.rule=Host(`hive.valtor.fi`)"
    - "traefik.http.routers.router-hive.entrypoints=websecure"
    - "traefik.http.routers.router-hive.tls.certresolver=resolveri"